FROM ubuntu:18.04
RUN apt update && apt install -y nodejs && apt install -y npm

#----------------Install frameworks------------------------

#CMD npm install express && npm install nodemon --save-dev \
#    npm i bcryptjs body-parser cors jsonwebtoken moment mongoose \
#    npm i morgan multer passport passport-jwt
#CMD tail -f /dev/null
